package com.ledze;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import java.util.Arrays;
import java.util.Collection;

/**
 * Source code generated by Gerardo Pucheta Figueroa
 * Twitter: @ledzedev
 * http://ledze.mx
 * 2/23/2017
 */
@SpringBootApplication
public class LedzedevCommandlinerunnerApplicationrunnerApplication {
    private static Logger logger = LoggerFactory.getLogger(LedzedevCommandlinerunnerApplicationrunnerApplication.class);

    public static void main(String[] args) {
        SpringApplication.run(LedzedevCommandlinerunnerApplicationrunnerApplication.class, args);
    }

    /**
     * Source code generated by Gerardo Pucheta Figueroa
     * Twitter: @ledzedev
     * http://ledze.mx
     * 2/23/2017
     */
    @Bean
    CommandLineRunner cargaEquiposClasicos(LigaRepository ligaRepository) {
        logger.info("Cargando con CommandLineRunner");
        return x -> {
            logger.info("CommandLineRunner tiene como parámetros un arreglo de Strings: "+ Arrays.toString(x));
            Arrays.asList(
                    new EquipoDeFutbol("América"),
                    new EquipoDeFutbol("Cruz Azul"),
                    new EquipoDeFutbol("Chivas"),
                    new EquipoDeFutbol("Pumas")
            ).forEach(e -> {
                logger.info(e.toString());
                ligaRepository.save(e);
                    });
            logger.info("Carga inicial finalizada.");
        };
    };

    /**
     * Source code generated by Gerardo Pucheta Figueroa
     * Twitter: @ledzedev
     * http://ledze.mx
     * 2/23/2017
     */
    @Bean
    ApplicationRunner cargaEquiposDelNorte(LigaRepository ligaRepository){
        logger.info("Cargando con ApplicationRunner");
        return x -> {
            logger.info("ApplicationRunner tiene como parámetro un objeto ApplicationArguments");

            logger.info("non option args: "+ Arrays.toString(x.getNonOptionArgs().toArray()) );
            logger.info("contiene files? "+x.containsOption("files"));
            logger.info("source args: "+ Arrays.toString(x.getSourceArgs()));
            logger.info("option values: "+x.getOptionValues("files"));
            logger.info("option names: "+x.getOptionNames());

            Arrays.asList(
                    new EquipoDeFutbol("Monterrey"),
                    new EquipoDeFutbol("Tigres"),
                    new EquipoDeFutbol("Xolos")
            ).forEach(e -> {
                logger.info(e.toString());
                ligaRepository.save(e);
            });
            logger.info("Carga equipos del norte finalizada");
        };
    };
}

/**
 * Source code generated by Gerardo Pucheta Figueroa
 * Twitter: @ledzedev
 * http://ledze.mx
 * 2/23/2017
 */
@RepositoryRestResource
interface LigaRepository extends JpaRepository<EquipoDeFutbol, Long> {
    Collection<EquipoDeFutbol> findByNombre(@Param("n") String nombre);
}

/**
 * Source code generated by Gerardo Pucheta Figueroa
 * Twitter: @ledzedev
 * http://ledze.mx
 * 2/23/2017
 */
@Entity
class EquipoDeFutbol {

    @Id
    @GeneratedValue
    private Long id;

    private String nombre;

    public EquipoDeFutbol() {
    }

    public EquipoDeFutbol(String nombre) {
        this.nombre = nombre;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Override
    public String toString() {
        return "EquipoDeFutbol{" +
                "id=" + id +
                ", nombre='" + nombre + '\'' +
                '}';
    }
}